name: h-former
channels:
    - conda-forge
    - anaconda
dependencies:
    - python>=3.9
    - pip>=22.1.2
    - pip:
          - jax>=0.3.13
          - jaxlib>=0.3.10+cuda11.cudnn82
          - tensorflow-gpu>=2.4.1
          - tensorflow-datasets>=4.5.2
          - numpy>=1.22.3
          - matplotlib>=3.5.1
          - imageio>=2.19.2
